name: CI
on: [push, pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      # - name: Cypress run
      #   uses: cypress-io/github-action@v5
      - name: Download Cypress
        uses: bahmutov/npm-install@v1
        with:
            install-command: npm i --force

      - name: Check Cypress cache
        run: |
            npx cypress cache path
            npx cypress cache list

      - name: restore / cache the binary
        id: cache-cypress
        uses: actions/cache@v1
        with:
            path: ~/.cache/Cypress
            key: >-
                cypress-cache-v2-${{ runner.os }}-${{ hashFiles('**/package.json')
                }}

      - name: Install Cypress
        run: |
            npx cypress install
            npx cypress cache list

      - name: Run Cypress
        continue-on-error: true
        run: npm run cy:run

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
            ref: allure
            path: allure

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
            allure_results: allure-results
            gh_pages: allure

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.TOKEN }}
            publish_branch: allure
            publish_dir: allure-history